imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    default_locale:  "%locale%"
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    session:
        storage_id: session.storage.php_bridge
        handler_id: ~

bartacus:
    plugins:
        resource: "%kernel.root_dir%/config/plugins.yml"
        strict_requirements: ~
#    dispatch_uris:
#        - /.../

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
